# $Id: npol.mac,v1.1 For running with or without visualization
# on the nmuNpol simulation 12/4/2013 $
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute npol.mac

#/vis/viewer/set/viewpointThetaPhi -45 180 deg
#/vis/viewer/zoom 1.5

/run/initialize
/run/verbose 0
#/event/verbose 0

/tracking/verbose 0
/tracking/storeTrajectory 1

#File name can be changed here
/analysis/setFileName npol_10Mevt_20MeV

#/gun/particle proton 
#/gun/particle pi0 
#/gun/particle mu- 
#/gun/particle anti_proton 
#/gun/particle neutron 
#/gun/energy 2.1 GeV
/gun/particle e-
/gun/energy 4400 MeV
/run/printProgress 10000
/run/beamOn 10000000

