# $Id: npol.mac,v1.1 For running with or without visualization
# on the nmu-Npol simulation 6/24/2016 $
# 
# This macro feeds commands to the primary event generator and allows 
# for changing of beam parameters within the macro. 
#
# can be run in batch, without graphic
# or interactively: Idle> /control/execute ElectronBeam.mac

#/vis/viewer/set/viewpointThetaPhi -45 180 deg
#/vis/viewer/zoom 1.5

/run/initialize
/run/verbose 0
#/event/verbose 0
/material/verbose 0
/cuts/verbose 0
/process/verbose 0

/tracking/verbose 0
/tracking/storeTrajectory 1

### GPS commands ####
# Particle type
/gps/particle neutron

# source: Beam, small diameter, no profile (yet), no rotation
/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/radius 5.0 mm
/gps/pos/sigma_r 0.0 mm
/gps/pos/centre 0. 5. 0. cm
/gps/direction -0.46947 0 0.882947

# the beam energy 
/gps/ene/type Mono
/gps/ene/mono 2110. MeV

#
# Commands below are independent of gps
#
/run/printProgress 1000
/run/beamOn 5000
