# $Id: npol.mac,v1.1 For running with or without visualization
# on the nmu-Npol simulation 6/24/2016 $
# 
# This macro feeds commands to the primary event generator and allows 
# for changing of beam parameters within the macro. 
#
# can be run in batch, without graphic
# or interactively: Idle> /control/execute ElectronBeam.mac

#/vis/viewer/set/viewpointThetaPhi -45 180 deg
#/vis/viewer/zoom 1.5

/run/initialize
/run/verbose 0
#/event/verbose 0
/material/verbose 0
/cuts/verbose 0
/process/verbose 0

/tracking/verbose 0
/tracking/storeTrajectory 1

### GPS commands ####
# Particle type
/gps/particle geantino

# the neutron beam energy is at 2100 MeV
/gps/ene/type Mono
/gps/ene/mono 2100. MeV

# source: Beam, small diameter, no profile (yet), no rotation
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 0.1 cm
/gps/pos/centre 0. 0. 0. cm
/gps/pos/rot1 -0.882947 0 -0.46947
/gps/pos/rot2 0 1 0
/gps/ang/type iso
/gps/ang/mintheta 0.0 deg
/gps/ang/maxtheta 5.00 deg
/gps/ang/minphi 0.0 deg
/gps/ang/maxphi 360.0 deg

#
# Commands below are independent of gps
#

/vis/scene/endOfEventAction accumulate 1000
/run/printProgress 10000

/run/beamOn 1000
