# $Id: npol.mac,v1.1 For running with or without visualization
# on the nmuNpol simulation 12/4/2013 $
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute npol.mac

#/vis/viewer/set/viewpointThetaPhi -45 180 deg
#/vis/viewer/zoom 1.5

/run/initialize
/run/verbose 0
#/event/verbose 0
/material/verbose 0
/cuts/verbose 0
/process/verbose 0

/tracking/verbose 0
/tracking/storeTrajectory 1

#/gun/particle proton 
#/gun/particle pi0 
#/gun/particle mu-
#/gun/particle anti_proton 
#/gun/particle gamma
#/gun/particle neutron 
#/gun/energy 2100 MeV #2.1 GeV

#/gun/particle e-
#/gun/energy 4400 MeV
#/run/printProgress 10000
#/run/beamOn 100

############# Command Test for GPS source #################

# Particle type
/gps/particle neutron

# source
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0. 0. 0. cm
/gps/pos/halfx 50. cm
/gps/pos/halfy 30. cm
/gps/direction -0.46947 0 0.882947
#/gps/pos/rot1 1 0 0
#/gps/pos/rot2 0 0 1

# Angular distribution supplied by user
#/gps/ang/type user
#/gps/hist/type theta
#/gps/hist/file UserTheta.dat

#/gps/hist/type phi
#/gps/hist/file UserPhi.dat

# energy distribution from user data
/gps/ene/type Arb
/gps/hist/type energy
/gps/hist/file macros/particleFluxData/neutronNpolFlux.dat
/gps/hist/inter Lin

# the beam energy is in gaussian profile centered at 4400 MeV
#/gps/ene/type Mono
#/gps/ene/mono 4400. MeV

#
# Commands below are independent of gps
#
/vis/scene/endOfEventAction accumulate 50
/run/printProgress 100

/run/beamOn 50
