# $Id: npol.mac,v1.1 For running with or without visualization
# on the nmuNpol simulation 6/23/2016 $
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute macro/PartilceFlux.mac

#/vis/viewer/set/viewpointThetaPhi -45 180 deg
#/vis/viewer/zoom 1.5

/run/initialize
/run/verbose 0
#/event/verbose 0
/material/verbose 0
/cuts/verbose 0
/process/verbose 0

/tracking/verbose 0
/tracking/storeTrajectory 1

# Particle type
/gps/particle neutron

# source
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0. 0. 0. cm
/gps/pos/halfx 50. cm
/gps/pos/halfy 30. cm
/gps/direction -0.46947 0 0.882947
#/gps/pos/rot1 1 0 0
#/gps/pos/rot2 0 0 1

# energy distribution from user data
/gps/ene/type Arb
/gps/hist/type energy
/gps/hist/file macros/particleFluxData/neutronNpolFlux.dat
/gps/hist/inter Lin

#
# Commands below are independent of gps
#
/vis/scene/endOfEventAction accumulate 50
/run/printProgress 100

/run/beamOn 50
